### ISSUE TITLE
Error when $crit_cpu_percent is true

### ISSUE THREAD

**Issue by b1oki** [andresgongora/synth-shell#132]
**Describe the bug**
Similar to #63, but problem with `top -d 0.1`
Error: `top: bad delay interval '0.1'`

**To Reproduce**
When CPU load average goes above determined critical value, status.sh fails to print *System Load*

**Screenshots**
![image](https://user-images.githubusercontent.com/1561897/62679854-2f090580-b9cf-11e9-9333-bb108293ff8a.png)

**Additional context**
Maybe this is `$(nice 'top' -b -d 0.1 -n 1 )` in `printHogsCPU()`
OS: Linux Mint 19.2
Kernel: 4.15.0-55-generic

**man top**
> -d  :Delay-time interval as:  -d ss.t (secs.tenths)
>             Specifies the delay between screen updates, and overrides the
>             corresponding value in one's personal configuration file or the
>             startup default.  Later this can be changed with the `d' or `s'
>             interactive commands.
>             \
>             Fractional seconds are honored, but a negative number is not
>             allowed.  In all cases, however, such changes are prohibited if
>             top is running in Secure mode, except for root (unless the `s'
>             command-line option was used).  For additional information on
>             Secure mode see topic 6d. SYSTEM Restrictions File.

**Comment by andresgongora** [comment]
Hi @b1oki. Sorry it's taking me so long to answer. I have no internet right now and it's a bit difficult to find a hot spot around here.

I'll take a look at the problem. In fact, I've already worked on it with @olmari (we had a private discussion outside github) but we tought it was solved. There is somehow a big version change or something going on with `top` and some distros still use the older (probably more stable) version of it and thus run into some issues.

I'll either change the way 'status.sh' uses `top` (i.e. resort to files under `/proc` instead) or add a version check to switch/adapt the command options as needed.

Please give me a while to work on it. It will take some time, but I haven't forgotten this issue ;)

**Comment by andresgongora** [comment]
I'm back from the dead. Let's take a look at this issue...

I've been trying to replicate the problem, and I'm quite sure it must be related to the `locale` fo your system. If you don't mind, could you test the following variaitons of `top` (notice that I'm replacing dots and commas):

- `top -d 0.1`
- `top -d 0,1`

**Comment by andresgongora** [comment]
I've been doing some tests on my machines and they all accept both, the period and the comma, as decimals mark. In both cases top works perfectly... however, after searching through the interwebs I've read several reports pertaining to this very problem. I think, at this point, that the `top` version that is powerted with Arch is more resilient than that with Ubuntu (or, the locale file alternatively); causing me to not be able to catch the error in time.

I think I've fixed it in 17aaf68 by computing a 1ms delay, storing it in a variable as 1/1000 (computed with `bc`), and then feeding it into top. I hope this works :) I will pull into master and close this issue. Please reopen it if the problem persits

**Comment by b1oki** [comment]
Hello, after update
```bash
top: bad delay interval '.00100'
:(
top: bad delay interval '.00100'
SYSTEM LOAD:  
```
```bash
++ awk '{avg_1m=($1)} END {printf "%3.2f", avg_1m}' /proc/loadavg
+ local current=1.06
++ nproc --all
+ local max=2
++ bc
+ local percent=53
+ '[' 53 -gt 40 ']'
++ bc
++ echo 'scale=5; 1/1000'
+ local delay=.00100
++ nice top -b -d .00100 -n 1
top: bad delay interval '.00100'

```
```bash
top -v
  procps-ng 3.3.12
Usage:
  top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
```

**Comment by andresgongora** [comment]
Dang! We didn't solve it :(
Could you please tell me what you get when you run these comands:
- `top -d 0.1`
- `top -d 0,1`

**Comment by b1oki** [comment]
Hooray! I think You have found the answer!

```bash
~ top -d 0.1
top: bad delay interval '0.1'

~ top -d 0,1
top - 19:46:25 up 7 days, 11:26,  1 user,  load average: 0,94, 0,98, 1,41
```

I don’t understand why the **man** says: `-d ss.t (secs.tenths)`

**Comment by b1oki** [comment]
replace code in **status.sh** to
```bash
local delay="0,1"
                local top=$(nice 'top' -b -d $delay -n 1 )
```
and get

![image](https://user-images.githubusercontent.com/1561897/64354067-2af4f580-d018-11e9-8764-1784ab52f1c9.png)

**Comment by andresgongora** [comment]
Hmm, the problem lies ineed in your locale config. The man says that because, for most language configuration, period (.) is used for decimal separation instead of comma (,). For example, my spanish system prints a comma when I press the dot button on my num-pad. On the other hand my english systems print a dot. That means, that when you pas 0.01 to top, it does not see a number, but a weird array.

The part I don't understand is why `bc` prints the decimals on your system with a dot, if your system uses comma. I use `bc`inside the script to convert 1/1000 to 0.001 in such a way that it **i expected** it would print 0,001 or 0.001 depending on the locale config, and thus provide the correct string to top.

I've just pushed to the develop branch a new change. Let's see if using `export LC_NUMERIC="C"` inside the script forces the thing to use periods instead of commas, without affecting your system.

The reason I can't just put a comma in the script is that half the users use dots, and the other half use coma :S

**Comment by b1oki** [comment]
![image](https://user-images.githubusercontent.com/1561897/64363707-bb3c3600-d02a-11e9-840b-f190d1328828.png)

**Comment by andresgongora** [comment]
I'm glad to hear that! Merging into Master and closing :)
