### ISSUE TITLE
Add root theme for fancy-bash-prompt.sh

### ISSUE THREAD

**Issue by kershov** [andresgongora/synth-shell#133]
There's no possibility to visually distinguish common user vs root/sudo user out of the box which can be slightly confusing. 

It would be nice to add additional variables for coloring ps1_user when user becomes root and add minor modification to `fancy-bash-prompt.sh`.

Something like:

```bash
local font_color_root="white"
local background_root="red"
local texteffect_root="bold"
```

```bash
if [ "`id -u`" -eq 0 ]; then
	local ps1_user=$(printSegment "\${FBP_USER}" $font_color_root $background_root $background_host $texteffect_root)
else
	local ps1_user=$(printSegment "\${FBP_USER}" $font_color_user $background_user $background_host $texteffect_user)
fi
```

**Before:**
![](https://i.imgur.com/ZZPVa6t.png)

**After:**
![](https://i.imgur.com/meDuOLl.png)

**Comment by olmari** [comment]
Can't root have it's own configfile, with own colorscheme already?

**Comment by kershov** [comment]
> Can't root have it's own configfile, with own colorscheme already?

OMG! It definitely can. I'm sorry for my dumbness... I didn’t even think about it as I work in a single-user environment with synth-shell installed for the only user I have in my system.

**Comment by andresgongora** [comment]
I will add a new issue to add a separate config file directly into root's folder (i.e. '/root/.config/') to address this issue from the start. It will be completely optional during installation, and only when selecting the system-wide option.

**Comment by b1oki** [comment]
> only when selecting the system-wide option

It may be possible to add the similar option for user installation in case of using the `sudo -s`?
Now it calls the script `status.sh` again.
