### ISSUE TITLE
Can't uninstall the scripts

### ISSUE THREAD

**Issue by BugAgain** [andresgongora/synth-shell#139]
**Describe the bug**
This uninstall procedure is not valid anymore:

**To Reproduce**
1. `git clone --recursive https://github.com/andresgongora/synth-shell.git`
2. `chmod +x synth-shell/setup.sh`
3. `synth-shell/setup.sh uninstall`
4. `rm -fr synth-shell`

**Expected behavior**
Uninstall

**Additional context**
Tested on Windows 10

**Comment by andresgongora** [comment]
Hi. Could you please provide more details?
Before uninstalling, does the script work as intended/expected? And after uninstalling (in this case, failed), do you still see the same when you fire up a new terminal?

Microsoft's bash implementation might not support one of the methods I'm using, so I need as much information as possible to pinpoint the issue.

Thanks

**Comment by BugAgain** [comment]
Sorry for the lack of the details, but I ended up uninstalling it by hand.

I think the biggest problem is in step 3
`synth-shell/setup.sh uninstall`

The method call isn't working on my experience in Windows 10 with my bash shell and, as you've mentioned, yes, I still see the same when you fire up a new terminal.

It can be very annoying for some curious users like me don't to be able to uninstall something that they don't understand well.

I don't know about bash script so much, but maybe someone else can make it work better on Windows for us.

**Comment by andresgongora** [comment]
Yes, I agree that it must be infuriating if you are just testing the script to see if you like it.

Let's try to get to the root of the problem. While running the uninstall script, do you remember if you got any sort of error message or info? Maybe Microsoft complained about certain action or something which could help us pinpoint the command that is failing.

The uninstall script shouldn't do anything fancy: just remove all script and config files (they are all together in the same folder), and remove the command that calls them when a new terminal is opened. Only that, remove files, remove call. But if you can still see everything, it means that it did neither.

Would you mind installing and uninstalling it again, and sending me the output of your terminal? Just of the uninstall script. Thanks

**Comment by BugAgain** [comment]
I got it working!

I tried to install it again, but this time with Ubuntu (wsl).

![install3](https://user-images.githubusercontent.com/29819739/67154155-5a607880-f2cd-11e9-8c60-cb4bf2c61c11.png)

I was trying to install it with **Git Bash** on the first try but I think I've done something wrong. Look:

![git_bash1](https://user-images.githubusercontent.com/29819739/67154173-d8248400-f2cd-11e9-961b-afe98cb28c34.png)

![git_bash2](https://user-images.githubusercontent.com/29819739/67154174-db1f7480-f2cd-11e9-9664-ad141397e576.png)

And when you try to uninstall, this is what happens:

![git_bash3](https://user-images.githubusercontent.com/29819739/67154182-04400500-f2ce-11e9-8fd9-a41d7c1db498.png)

Then you have to try to remove it manually and deleting these two files located in `C:\Users\{the_user}` solved for me for now.

![git_bash4](https://user-images.githubusercontent.com/29819739/67154193-48330a00-f2ce-11e9-91d7-62a9b0a251f3.png)

You may not need any corrections in the scripts. It might be possible to install with **Git Bash** as well, but I think some workaround is needed.

Anyway, if you need any extra non-sensitive information, just ask. It's a pleasure to collaborate. Thank you for your time doing this!

**Comment by andresgongora** [comment]
I'm glad it worked for you, even though you had all the problems. I've never tested it on Windows, but I'll try to come around it sometime in the future and fix all the bugs/errors. Thanks for all the info and taking your time to post the many screenshots! :)
