### ISSUE TITLE
weird command prompt output

### ISSUE THREAD

**Issue by toter200** [andresgongora/synth-shell#147]
I just installed synth-shell through the setup.sh script. I get this weird behavior 
![image](https://user-images.githubusercontent.com/26483509/71373159-81317880-25b6-11ea-960f-64c613573dc4.png)

I'm on Arch with awesomeWM. I have no idea what might cause this and don't know how to look for a solution

**Comment by andresgongora** [comment]
Did you remember to install `power-fonts` or `fonts-power` as described in the instructions? Those weird characters are the "triangle" separators, but usually you need an extra font to show them properly. Please confirm whether the error persists or goes away :)

**Comment by dzionek** [comment]
Apart from installing powerline fonts `sudo pacman -S powerline-fonts`, you need to check if your locales are configured appropriately. Run `locale` and verify if they are set to UTF-8. If not, edit your `/etc/locale.conf`

More info: [https://wiki.archlinux.org/index.php/locale](url)

**Comment by toter200** [comment]
Apparently i had no locale.conf. Indeed creating it and changing the Encoding to UTF-8 fixed the error.
Thank you very much.

**Comment by andresgongora** [comment]
Thanks @dzionek. I added a note to the README in `develop` in b61f4bf. It will slowly make its way to `master` to avoid future issues like this :)
