### ISSUE TITLE
synth-shell-master/bash-tools is empty

### ISSUE THREAD

**Issue by tulipb** [andresgongora/synth-shell#159]
**Describe the bug**
setup.sh hangs cycling between:
./setup.sh: line 380: /home/boris/!/synth-shell-master/bash-tools/bash-tools/user_io.sh: No such file or directory
./setup.sh: line 381: printHeader: command not found

appeared that synth-shell-master/bash-tools is just empty

**To Reproduce**
1. clone master repo, 
2. unpack
3. run setup.sh

**Expected behavior**
installation process success

**Screenshots**
./setup.sh: line 380: /home/boris/!/synth-shell-master/bash-tools/bash-tools/user_io.sh: No such file or directory
./setup.sh: line 381: printHeader: command not found

**Comment by tulipb** [comment]
sorry, recursive clone...

**Comment by andresgongora** [comment]
No problem. I hope you like the scripts :)

**Comment by Pantar2205** [comment]
hey i have this error and i don't understand the reference recursive clone. im asking for help because i can't figure this out. i have this setup on another machine and i love it so much, just want to also have it on my laptop if possible.

**Comment by andresgongora** [comment]
Please, run the following and let me know if it works:
`git clone --recursive https://github.com/andresgongora/synth-shell.git && chmod +x synth-shell/setup.sh && synth-shell/setup.sh`

**Comment by Pantar2205** [comment]
> Please, run the following and let me know if it works:
> `git clone --recursive https://github.com/andresgongora/synth-shell.git && chmod +x synth-shell/setup.sh && synth-shell/setup.sh`

Thank You so much.
Have it on my Desktop, TV & laptop now, love it so much!! Thank You!!
