### ISSUE TITLE
system-wide configuration directory is wrong in status.sh

### ISSUE THREAD

**Issue by zzhou02** [andresgongora/synth-shell#175]
**Describe the bug**
I was trying to customize the logo with a system-wide installation, but it produce no effect at all. The config file path should be /etc/synth-shell/status.config, but I found the path in status.sh to be: local sys_config_file="/etc/andresgongora/synth-shell/status.config" (line 1253). I changed the file path in status.sh and the logo can be changed after re-installation. 

**To Reproduce**
1. System-wide install with status.sh
2. Modify logo in /etc/synth-shell/status.config
3. Start a new terminal window
4. See no change in logo

**Expected behavior**
Logo should be changed. 

**Additional context**
The path on line 1253 in status.sh should be changed to the correct one in README.md
P.S. this is my first issue. Please ask me more information if needed. Thanks!

**Comment by andresgongora** [comment]
```
Sorry for the late reply. I have several major projects going on and so I was unable to address all issues of this repo. I'm a bit more free now and so we should be able to fix all issues in a short time.

Please let me remind you that synth-shell is going through a big change. I'm moving all script inside synth-shell to external repos, so that they now becomes submodules that can, if the user wishes so, be installed completely independently. This is a big improvement, but requires a lot of work. Just as a brief overview:

- synth-shell https://github.com/andresgongora/synth-shell: this will be the parent repo. Eventually it will contain little code on its own and will become a bundle of submodules.

- bash-tools https://github.com/andresgongora/bash-tools: all auxiliar functions that have "generic" use will be store here. Like printer helpers and such.

- synth-shell-greeter https://github.com/andresgongora/synth-shell-greeter, formerly known as status.sh, is the script that prints the logo and system status info.

- synth-shell-prompt https://github.com/andresgongora/synth-shell-prompt: prints a nice colored prompt with triangles.
```
Hi @zzhou02 , thanks for the bug report. I think this issue is tightly tied to the other bugs the script has. Please consider reinstalling synth-shell, I have updated the master branch heavily. Please let me know if doing so fixes the bug or other new ones appear.

**Comment by andresgongora** [comment]
The system-wide setup might have suffered during the last merge. It's been a complete mess, really. Please try again and let me know if it works now. If not I'll give it a go and clean it up. Thanks so much for your help. I have like 10 critical open issues atm and its a bit overwhelming hehehehe

**Comment by zzhou02** [comment]
Hi, I'm glad that you come back to this project! I tried to reinstall with a system-wide setup just now, but unfortunately it doesn't work for me. After a fresh clone and installing the submodules with `git submodule init` and `git submodule update` (I assume that's how it works? I'm not really familiar with git yet), the system-wide setup seems to go into an infinite loop. Here's the screenshot:  
![synth_shell](https://user-images.githubusercontent.com/54516410/84628055-d5018800-ae9c-11ea-8576-e37b311c90ec.png)

Sorry if my installation method was wrong, and I suggest you update the README with the intended commands to make it work. Thank you!

**Comment by andresgongora** [comment]
I think you updated everything properly :) The problem is the system-wide setup... right now it's a complete mess. Let me have a look at it and I'll be back.

**Comment by andresgongora** [comment]
Ok. I think it works now, but it still needs more testing.
Could you change from the `master` branch to `develop`? They are identical but I have re-enabled the system-wide options in the `develop` branch. Once we fix it, I'll move it to `master`.

I tried it on my system and it worked. But because this is so dependent on your setup, it might fail for some unexpected/weird reason.

Also, I have **not** implemented the system wide uninstall yet. To remove the script, you have to manually disable it in your system-wide `/etc/bash.bashrc` file if something goes wrong ;)

**Comment by zzhou02** [comment]
Hi, sorry for the late reply. I tested the system-wide installation, and it works great except the user name is not displayed correctly when switching to root user. It still displays my non-root user name. Here are the screenshots of before the installation and the after the installation: 
![without_synth](https://user-images.githubusercontent.com/54516410/84972849-9524e580-b0d4-11ea-80cb-4da448dc502d.png)
![with_synth](https://user-images.githubusercontent.com/54516410/84972977-d5846380-b0d4-11ea-81ba-e2021cf723af.png) Everything else works perfectly except that little bug. Thanks!
P.S. the system-wide uninstallation seems to work for me.

**Comment by andresgongora** [comment]
Hmmm not sure here. I believe that even if you use `su` the `/etc/bash.bashrc` is not read again. Can you try to log in a new session directly into your root account? For example, use ctrl+alt+F2 to open tty (if F2 does not work, try all other Fs). Let me know if it worked in your case, otherwise there is a bug :S

**Comment by zzhou02** [comment]
Yeah it works correctly when I log into another session with root. Somehow the better-ls is not working for me under system-wide config (which works in user-only config). I think it might be that all the installings and uninstallings have messed up my config overall. Personally I'll just stick with user-only configuration for now. Thank you for your efforts!
