### ISSUE TITLE
light-purple background not working

### ISSUE THREAD

**Issue by kireita** [andresgongora/synth-shell#200]
Hey,

im trying to set a purple/light-purple themed console but wherever i type 'light-purple' the console shows no background.
![image](https://user-images.githubusercontent.com/25864917/117531969-7168d780-afe5-11eb-95ac-9532b74e5083.png)

**Comment by kireita** [comment]
no worries, i used the number-colors instead

**Comment by andresgongora** [comment]
It only recognized `light-magenta` instead of `light-purple`. I've added both of them now to the develop branch and it will eventually make it into master. I'm glad you could fix it using the color codes meanwhile :)
