### ISSUE TITLE
Conda environment support

### ISSUE THREAD

**Issue by Nootaku** [andresgongora/synth-shell#205]
As a  (Mini)Conda user, I often change my python environment using `conda activate env`.
In a regular terminal, I get my current active environment at the start of my path info: `(myenv) myuser@hostname $ ~`

I've noticed that, despite the presence of a PYENV, my conda environment is not displayed.

Is this a bug or a feature request ?

**Comment by andresgongora** [comment]
Hi Nootaku, this is a feature request related to: https://github.com/andresgongora/synth-shell-prompt/issues/16
I'll close this ticket for now :)
