### ISSUE TITLE
Putty colors

### ISSUE THREAD

**Issue by simpsss** [andresgongora/synth-shell#218]
Hello,

The colors don't change, I change the colors, but it's always red in the user and folder.

Can you help me?

![image](https://user-images.githubusercontent.com/51731449/149967759-d9429ea4-17a2-429b-b5d7-2dc8e0bbf3db.png)

**Comment by andresgongora** [comment]
Hi! You are seeing the synth-shell configuration for root (are you sure you
want to log in as root?) to change it you have to edit the configuration
under /root/.config/synth-shell. Let me know if that worked. BR

**Comment by andresgongora** [comment]
Oh yeah, if there is no config at all there, then the script might be using
the default values. Just create the aforementioned path and place your
config files in there, it should work for your next bashrc reload. Note
that I've never really debugged the script for root :)

**Comment by simpsss** [comment]
yeah, i was using the root account..

I tested using a normal/root user and it worked.

Thanks
