### ISSUE TITLE
How to change the text color ?

### ISSUE THREAD

**Issue by wadkarkundan** [andresgongora/synth-shell#227]
So I have made my changes in the .config file to suit my setup but the Text color by default is Blue how to change it to white or something else
![Screenshot from 2022-05-19 19-10-27](https://user-images.githubusercontent.com/89029184/169307404-5e0e585b-707f-40fe-a599-f9746105b201.png)

the Font Color I mean when we type in commands its blue by default.

**Comment by ibndiaye** [comment]
Also looking for a solution, ill keep you posted

**Comment by andresgongora** [comment]
In the config file, you should be able to tweak the color by changing `format_info="-c white"`to any color you like ;)

**Comment by Radius112** [comment]
> In the config file, you should be able to tweak the color by changing `format_info="-c white"`to any color you like ;)

what config file?

**Comment by ben-alkov** [comment]
> In the config file, you should be able to tweak the color by changing format_info="-c white"to any color you like ;)

AFAICT, this simply isn't the case. `format_info` only changes the color of the "categories" in the greeter.

e.g., from

```
OS              Fedora Linux 37 (KDE Plasma)
Kernel          6.1.10-200.fc37.x86_64
CPU             11th Gen Intel Core i7-11850H
...
```

"OS, "Kernel", and "CPU" are controlled by `format_info`

Looks like it's actually `font_color_input`, in "~/.config/synth-shell/synth-shell-prompt.config"

**Comment by andresgongora** [comment]
Ohh I bad. Indeed. Setting the color for your command, what you type into the terminal, is controlled by `font_color_input` in `~/.config/synth-shell/synth-shell-prompt.config`.

I think @ben-alkov hit the nail on the head. I'm closing this issue but feel free to reopen it if you still have problems getting the colors you want
