### ISSUE TITLE
Unable to change host in synth-shell-prompt.config 

### ISSUE THREAD

**Issue by cumironin** [andresgongora/synth-shell#233]
**Describe the bug**
Unable to change HOST at .config

**To Reproduce**
Insert HOST=".." 

**Expected behavior**
Host will change whenever i  insert

**Comment by cumironin** [comment]
> Hi. `HOST` is not a valid configuration option in `synth-shell-prompt.config`. You can change the disposition of the prompt, though. Is that what you are trying to achieve? In that case, yes, you should be able tho change the order of the prompt by moving `HOST` around. By default, the order is `format="USER HOST PWD GIT PYENV TF"`.
> 
> On the other hand, to change your hostname edit your `/etc/hostname` file as described for example here: https://wiki.archlinux.org/title/Network_configuration#Set_the_hostname
> 
> @cumironin please confirm whether I understood your problem ;)

Yes, thank your for your explanation

**Comment by andresgongora** [comment]
Is it solved then? If not, could you elaborate on what it is you'd like to achieve?

**Comment by andresgongora** [comment]
Awesome!
