### ISSUE TITLE
better-ls not listing subdirectory

### ISSUE THREAD

**Issue by croMicLi** [andresgongora/synth-shell#240]
**Describe the bug**
better-ls does not list a subdirectory

**To Reproduce**
With synth-shell installed:
1. Go to your home directory
2. mkdir test1
3. cd test1
4. mkdir test2
5. cd test2
6. mkdir test3
7. cd ~
8. mv test1/ Downloads
9. cd Downloads
10. cd test1
11. cd test2
12. ls
The "test3" directory will not be shown, but ls -a does show it.
Removing better-ls from the .bashrc fixes this, adding it again
caused the issue to appear once more. Did this several times 
to confirm that it was connected to better-ls.

Tested on Ubuntu 22.04 and on Kubuntu 22.10.

**Expected behavior**
The "test3" subdirectory should be listed.

**Comment by andresgongora** [comment]
Hmmm yup, I can confirm that I can replicate this issue. I guess it has something to do with the amount of recursiveness in the script. I'll have a go at it

**Comment by andresgongora** [comment]
This should be fixed now in bc2b3af. It was a typo where better-ls did not properly check if the current directory had files/folders that needed to be displayed. Feel free to reopen the issue if the problem persists, and thanks for catching the bug :)
