### ISSUE TITLE
Prompt shows ".." instead of "~" for config dir

### ISSUE THREAD

**Issue by yani** [andresgongora/synth-shell#243]
When navigating to `~/.config/synth-shell` the prompt shows `../.config/synth-shell` instead of `~/.config/synth-shell`.

(Wrong icon for home dir)

![image](https://user-images.githubusercontent.com/6956790/216827834-5ad14003-0c33-4ba2-9cf8-2340a8f0ea73.png)

My setup is all included scripts and I only removed the HOST in the prompt and changed the user color to purple.

**Comment by andresgongora** [comment]
You are right, I had never noticed. This only happens in very rare occasions where the current $PWD path has exactly the same length as the requested character limit.

This should be fixed with d82a0e7, but feel free to reopen this issue if your problem persists
