### ISSUE TITLE
Glitched looking name system and directory blocks

### ISSUE THREAD

**Issue by RobCod** [andresgongora/synth-shell#244]
**Describe the bug**
Installed with the bash script, have all the fonts mentioned installed and double checked that my locale is UTF8
![image](https://user-images.githubusercontent.com/48031674/217466443-dcb6d6e6-b02d-4a9d-a222-39ddbed5545f.png)

I had it working fine on my previous install, but after I reinstalled my OS i have been given this as a result (stupid me forgot to backup my .bashrc folder from my previous install)

**Comment by andresgongora** [comment]
Have you tried changing your terminal's font to something like hack-ttf?
https://github.com/source-foundry/Hack

**Comment by andresgongora** [comment]
Did it work? Let me know ;)

**Comment by RobCod** [comment]
Yes my apologies, about 3 days ago right after I posted I changed the font to Iosevka Term Regular and it solved my issues
