### ISSUE TITLE
prompt looks weird.

### ISSUE THREAD

**Issue by sojjan1337** [andresgongora/synth-shell#245]
Hi!

Don't know why it looks like this after install: 

![Screenshot from 2023-03-24 18-28-09](https://user-images.githubusercontent.com/44612734/227598334-9e1443e0-4ddd-4dda-a7ad-9462acdbad31.png)

Using Fedora 37

Thanks!

**Comment by andresgongora** [comment]
Hi. have you installed powerline-fonts? Try changing your terminals font.
Let me know if it works

**Comment by sojjan1337** [comment]
Is there a way to hide you username and hostname? It get's kind of long.

**Comment by andresgongora** [comment]
Yes. In the config file
