### ISSUE TITLE
The cd command lists wrong information

### ISSUE THREAD

**Issue by ArnaudCHEVALME** [andresgongora/synth-shell#247]
**Describe the bug**
After a clean install on Ubuntu 23, typing cd and hitting tab a few times lists all kind of things

**To Reproduce**
1. Install synth-shell for the current user
2. Go to an empty folder
3. Type the cd command and hit tab a few times
5. See error

**Expected behavior**
Nothing should happen

**Screenshots**
![image](https://github.com/andresgongora/synth-shell/assets/114645588/6d22455e-c5b5-414b-9a57-cd23a794c863)

**Comment by andresgongora** [comment]
I'm unable to reproduce your bug. Did you fix it?

**Comment by ArnaudCHEVALME** [comment]
Yes, it had nothing to do with this amazing project and and was just a misconfiguration of my command completion. Sorry for the unneeded issue !

**Comment by andresgongora** [comment]
No problem! I'm glad you managed to fix it!
