### ISSUE TITLE
Unable to install. bash-tools: No such file or directory

### ISSUE THREAD

**Issue by vin01k** [andresgongora/synth-shell#249]
I have a amazon linux 2 workspace. Previously I'd installed the synth-shell but it doesn't have the new line feature that this one has so I uninstalled the synth-shell and decided to install synth-shell-prompt.

Per the readme, I pulled the git repo and ran the synth-shell-prompt/setup.sh command and encountered this error:

```
user_io.sh: line 32: cd: /home/vin/gitstuff/bash-tools/bash-tools: No such file or directory
Include failed /home/vin/gitstuff->bash-tools/bash-tools/hook_script.sh
```

Also, my prompt looks weird after the uninstallation of previous shell.
![image](https://github.com/andresgongora/synth-shell/assets/144093011/be94259a-0e51-43f0-97ea-6d01444057f2)

Can someone please help me with the installation?

**Comment by vin01k** [comment]
Hi, I've fixed this myself. I was in the wrong directory lol.

**Comment by olmari** [comment]
Glad to hear :)
