### ISSUE TITLE
Terminal no longer starts up in home directory

### ISSUE THREAD

**Issue by awkto** [andresgongora/synth-shell#250]
**Describe the bug**
After installing synth, my terminal no longer starts up in my home directory. Instead it always starts up in the folder where I had cloned the synth git repo (/home/username/repos/synth-shell)

**To Reproduce**
1. Clone repo on Fedora 38
2. CD into the cloned folder
3. Install synth
4. Restart terminal 

**Expected behavior**
My terminal should continue to start in my home directory

**Comment by andresgongora** [comment]
That is VERY odd. Your .bashrc file will 'source' the script and just run
it, it should not 'cd' to the script's folder. Do you observe any other
errors? Does the script work as expected? Also, if you uninstall it (or
comment it out in your bashrc file) does it revert back to the correct
behavior?

**Comment by awkto** [comment]
Commenting out the scripts showed me the issue was on my end, as it was still happening.
Turns out I had some terminal window still open, and by default it always opens to the same directory if one window is already open. Closing out

**Comment by awkto** [comment]
Issue unrelated to synth
