### ISSUE TITLE
Additional built-in visual themes

### ISSUE THREAD

**Issue by awkto** [andresgongora/synth-shell#251]
**Is your feature request related to a problem? Please describe.**
Not related to a problem really. I just can't come up with good looking themes myself and it is cumbersome modifying individual color variables to try and make things look good. I think adding a few color options would be very good for new users

**Describe the solution you'd like**
When you install synth-shell, there should be a couple options for various themes (default, red, green, purple, neon, dull, etc)

**Describe alternatives you've considered**
Either during the install script, or post-install if there is a simple variable to change, OR a place online where people can post and share synth themes.

**Comment by andresgongora** [comment]
Have you had a look at
https://github.com/andresgongora/synth-shell-greeter/tree/b345b0ab19d3a33555bbb68390305f28b6a6ef3a/synth-shell-greeter
and
https://github.com/andresgongora/synth-shell-prompt/tree/876cfed759e09bc535423887268b43d5e6fe8a81/config/examples
?

**Comment by awkto** [comment]
Oh cool, I see it now! Thank you!
