### ISSUE TITLE
custom prompt only for root kali

### ISSUE THREAD

**Issue by PitiPipouSauvage** [andresgongora/synth-shell#258]
I installed synth-shell on a kali linux machine and i tried to do user installs and global installs. It only seems to work out for the root user. I saw someone already had this issue but it didn't work for me. 
![image](https://github.com/andresgongora/synth-shell/assets/96929981/c7bd1078-0c76-435e-937d-87a8606f0836)

**Comment by andresgongora** [comment]
Can you confirm synth-shell is included in your user's bashrc file? Maybe
kali uses something different... please look under your user's home folder
for the file .bashrc, and at the end of it there should be a hook for synth
shell (if you installed it for your user). If you did global install, then
it should be sourced for all users. Did you try to log out and back in?

**Comment by PitiPipouSauvage** [comment]
It is linked on my root's .bashrc file but not on my user's .bashrc file

**Comment by PitiPipouSauvage** [comment]
It worked doing it this way
