### ISSUE TITLE
Greeter, 'bc' not found.

### ISSUE THREAD

**Issue by DeadPuddle** [andresgongora/synth-shell#262]
Occurs upon opening terminal.

![Screenshot from 2024-01-21 18-23-59](https://github.com/andresgongora/synth-shell/assets/69779479/da740b76-35b2-4fe5-90fe-cfba06dd58a3)

**Comment by andresgongora** [comment]
Please install the bc package. It's a terminal calculator. On Ubuntu and
arch it's called just that, bc.

It's a bit old. Maybe I should replace this dependency with something else

Cheers!

**Comment by DeadPuddle** [comment]
Somehow I wasn’t able to find this package when searching with pacman. Many thanks!

**Comment by DeadPuddle** [comment]
Somehow I wasn’t able to find this package when searching with pacman. Many thanks!
